CREATE TABLE IF NOT EXISTS "AP#MERCHANTS" (
    MERCID NUMBER PRIMARY KEY,
    NAME VARCHAR2(256) NOT NULL,
    HIERARCHYID NUMBER,
    PALOGIN VARCHAR2(16),
    PAPASSWORD VARCHAR2(16),
    APILOGIN VARCHAR2(16),
    APIPASSWORD VARCHAR2(256),
    INITIATOR VARCHAR2(64) NOT NULL,
    CIRCUIT VARCHAR2(8)
);

CREATE TABLE IF NOT EXISTS MERC_CONFIG (
    MERCID NUMBER NOT NULL,
    PARAMETERNAME VARCHAR2(32) NOT NULL,
    PARAMETERVALUE VARCHAR2(128) NOT NULL,
    DATEBEGIN TIMESTAMP NOT NULL,
    DATEEND TIMESTAMP NOT NULL,
    PRIMARY KEY (MERCID, PARAMETERNAME, DATEBEGIN, DATEEND)
);
