CREATE TABLE IF NOT EXISTS "AP#MERCHANTS" (
    MERCID NUMBER PRIMARY KEY,
    NAME VARCHAR2(256) NOT NULL,
    HIERARCHYID NUMBER,
    PALOGIN VARCHAR2(16),
    PAPASSWORD VARCHAR2(16),
    APILOGIN VARCHAR2(16),
    APIPASSWORD VARCHAR2(256),
    INITIATOR VARCHAR2(64) NOT NULL,
    CIRCUIT VARCHAR2(8)
);

CREATE TABLE IF NOT EXISTS MERC_CONFIG (
    MERCID NUMBER NOT NULL,
    PARAMETERNAME VARCHAR2(32) NOT NULL,
    PARAMETERVALUE VARCHAR2(128) NOT NULL,
    DATEBEGIN TIMESTAMP NOT NULL,
    DATEEND TIMESTAMP NOT NULL,
    PRIMARY KEY (MERCID, PARAMETERNAME, DATEBEGIN, DATEEND)
);

CREATE TABLE IF NOT EXISTS TERMINALSETTINGS (
    MERCID NUMBER NOT NULL,
    MPS VARCHAR2(10) NOT NULL,
    GATE VARCHAR2(10) NOT NULL,
    IS3DS NUMBER NOT NULL,
    TERMINALID VARCHAR2(20),
    MERCHANTID VARCHAR2(20),
    MCC VARCHAR2(10),
    NAME VARCHAR2(64),
    MERCHANTURL VARCHAR2(100),
    LOGIN VARCHAR2(32),
    PASSWORD VARCHAR2(32),
    APIURL VARCHAR2(64)
);
